name: python-code-analysis

on:
  push:
    branches  :
      - master
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements_dev.txt
    - name: Run Migrations
      run: python manage.py migrate
    - name: Run Tests
      run: |
        python manage.py test

  sonarqube:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarQube Scan
      run: Sonar-Scanner \
             -Dsonar.projectKey=Python-code \
             -Dsonar.sources=. \
             -Dsonar.host.url=http://20.121.69.96:9000 \
             -Dsonar.token=sqp_bd8d6f4dd6aeed7fbc6c768a8cb37af55b81f4b6
     
